# Generated by Django 3.2.3 on 2021-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productPrice', models.IntegerField()),
                ('productQuantity', models.IntegerField()),
                ('productSize', models.CharField(max_length=50)),
                ('productColor', models.CharField(max_length=50)),
            ],
        ),
    ]
