# Generated by Django 3.2.3 on 2021-07-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0002_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
